### ISSUE TITLE
Suggestions for next step: metric calculation to own function

### ISSUE THREAD

**Issue by bpbond** [jk-brown/matilda#1]
Move the metric calculation out of `iterative_hector` and into its own function. Users will then do something like this:
```r
results <- iterative_hector(core, ...)  # this produces d.f. of N runs x Y years of data
metric_calc(results, op, var, years) # this produces d.f. of N 
```

Inside of `metric_calc`: you want to split up the results d.f. and call `metric_calc_1run` for each run of data. There are a number of ways to do this, but in base R (which you're using 🎉 ) I would suggest `split` followed by `sapply`.

**Comment by bpbond** [comment]
...and then we will WRITE TEST CODE FOR THESE!!! WOT

**Comment by ecolo-joe** [comment]
Created a new branch (`metric_calc-function-dev`) where I have a metric_calc.R file with what I think produces the output we are looking for, but with some missing parts (a column for variable names) 

For adding the variable names column I started a second branch. Want to make it so that the output is accurate for cases where the user wants metrics for multiple variables.

**Comment by ecolo-joe** [comment]
I will start thinking about issue #2 today

**Comment by bpbond** [comment]
Hmm, I don't totally understand what's going on above I guess. I thought you could simply do

```r
  x_split <- split(x, x$run_number)
  metric_result <- sapply(x_split, metric_calc_1run, var, op, years)
```
and get back a vector of run numbers + metric values. No?

**Comment by ecolo-joe** [comment]
Yes, I have that in the first development branch (`metric_calc-function-dev`):

```r
metric_calc <- function(x, op, var, years) {

  # Splitting x (df of hector output) by run number
  result_split <- split(x, x$run_number)

  # calculating metric for split result using metric_calc_1run
  metric_result <- sapply(result_split, metric_calc_1run, op, var, years)
```
So I have that saved elsewhere.

But that function does not produce an accurate result if the user supplies a variable list instead of a single variable because it only splits the hector result by run_number.

so if the user runs hector on a variable list, and then passes that variable list to `metric_calc` it looks like this:

```r
var_list <- c("global_tas", "RF_tot", "CO2_concentration")
metric_calc(result, mean, var = var_list, 2000:2100)
```
the return is the mean of all the variables in `var_list` , but grouped by run_number alone (which obviously isnt an accurate result):

```r
run_number             metric_value
1                      144.3644
2                      142.1964
3                      145.7821
4                      139.9651
5                      142.1424
6                      142.6751
7                      153.9986
8                      139.8318
9                      149.8277
10                     142.3779
```
And then once I get to the step of adding variable names to a return df, it will hit the user with error because you are asking to assign what should be 30 variable rows (10 runs for each of 3 variables) to a result that only produces 10 rows. 

So anyway, all that to say that the above function works fine if a single variable is supplied. But not if a variable list is supplied.

Maybe thats not a concern, but I imagine someone will want to get metrics for more than one variable at a time. since the `metric_calc` function that can accept multiple variables is in a separate branch, we can scrap it if it isn't something we are looking for.
