### ISSUE TITLE
Edits to scoring functions

### ISSUE THREAD

**Issue by jk-brown** [jk-brown/matilda#53]
I edited the scoring functions (now `score_ramp` and `score_bayesian`) and `score_hruns` to work the way we described in our meeting on Wednesday.

Here is where I have my notes stored:
https://github.com/jk-brown/matilda_notes/blob/main/editing_score_functions.Rmd

I think I have the main idea of what we discussed but if there is anything you think is redundant or weak programming-wise.

thanks!

**Comment by bpbond** [comment]
Hi @jk-brown that looks good! A few thoughts:
* I would suggest not naming the parameter to the scoring functions as `matrix`, which is a pre-existing function in R. Use `m` or `mtrx` or something like that
* The loop condition `i in 2:ncol(matrix)` will break is the matrix has less than two columns. Consider putting a defensive programming `stopifnot(ncol(matrix) < 2)` to check this at the beginning of the function
* This `obs_data <- matrix[, 1]` only needs to be executed _once_, before the loop starts, since it'll never change; this also applies to the checks on `w1` and `w2` in `score_ramp`
